name: Flatpak

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: xyz.ketok.Speedtest.flatpak
        manifest-path: xyz.ketok.Speedtest.yml
        cache-key: flatpak-builder-${{ github.sha }}
    - uses: flatpak/flatpak-github-actions/flat-manager@v4
      with:
        repository: ketok-nightly
        flat-manager-url: https://flatpak-api.ketok.xyz
        token: ${{ secrets.FLATPAK_TOKEN }}
